// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/wowqhb/goframe_demo/model/internal"
)

// Book is the golang structure for table book.
type Book internal.Book

// Fill with you ideas below.
