// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"goframe_dome/dao/internal"
)

// bookDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type bookDao struct {
	*internal.BookDao
}

var (
	// Book is globally public accessible object for table book operations.
	Book = &bookDao{
		internal.Book,
	}
)

// Fill with you ideas below.
