// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Book is the golang structure for table book.
type Book struct {
	Book  string `orm:"book,primary" json:"book"`  // book name
	Price int    `orm:"price"        json:"price"` // book price
}
